application: gcpjekyll
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: \1
  upload: (.*\.(appcache|manifest))

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: \1
  upload: (.*\.ico)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: \1
  upload: (.*\.json)

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: \1
  upload: (.*\.swf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

# clean urls
- url: /(.+)
  mime_type: text/html
  static_files: \1.html
  upload: (.+)

# index files
- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html

- url: /(.+)
  static_files: \1/index.html
  upload: (.+)/index.html

# site root
- url: /
  static_files: index.html
  upload: index.html
